spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.202.67.10:33068/tetonam?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: "root"
    password: "ssafy108"

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true

jwt:
  secret : upRb3244Zp+WmAEt/qCnLnhBEvIu4xc3u+nqF/KdjiJ/dImoYrOfd7GYSy0L3o6zWnz+9BgcjjhiN5mw9Y241A==
server:
  address: 0.0.0.0
  port: 8080
