services:
  frontend:
    build:
      context: ../frontend/tetonam
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_AGORA_APP_ID: ${VITE_AGORA_APP_ID}
    container_name: tetonam-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - tetonam-network

networks:
  tetonam-network:
    external: true
