version: '3.8'

services:
  backend:
    build:
      context: ../backend
    container_name: backend
    ports:
      - "8080:8080"  # 필요시 생략 가능
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: redis
      JWT_SECRET: ${JWT_SECRET}
      CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      CLOUD_AWS_REGION_STATIC: ${CLOUD_AWS_REGION_STATIC}
      S3_URL: ${S3_URL}
      AGORA_APP_ID : ${AGORA_APP_ID}
      AGORA_APP_CERTIFICATE : ${AGORA_APP_CERTIFICATE}
    env_file:
      - ../deploy/.env
    networks:
      - tetonam-network

networks:   # 도커 간 같은 네트워크 사용
  tetonam-network:
    external: true