services:
  frontend:
    build:
      context: ../frontend/tetonam
    container_name: tetonam-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ../deploy/.env
    networks:
      - tetonam-network

networks:
  tetonam-network:
    external: true