version: '3.8'

services:
  # --- AI ---
  ai:
    build:
      context: ../AI
    container_name: ai-fastapi
    restart: always
    ports:
      - "8000:8000"
    networks:
      - tetonam-network

networks:   # 도커 간 같은 네트워크 사용
  tetonam-network:
    external: true