spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8   # EC2
    # url: jdbc:mysql://127.0.0.1:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8   # localhost
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  redis:
    # host: localhost     # localhost
    host: redis           # EC2
    port: 6379

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true

jwt:
  secret : ${JWT_SECRET}
server:
  address: 0.0.0.0
  port: 8080
